services:
  postgres:
    image: postgres:15-alpine
    container_name: arxiv_postgres
    environment:
      POSTGRES_DB: arxiv_curator
      POSTGRES_USER: curator
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-secretpassword}
    volumes:
      - ./volumes/postgres_data:/var/lib/postgresql/data
      - ./database/init:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U curator -d arxiv_curator"]
      interval: 10s
      timeout: 5s
      retries: 5

  pipeline:
    build: .
    container_name: arxiv_pipeline
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      DATABASE_URL: postgresql://curator:${POSTGRES_PASSWORD:-secretpassword}@postgres:5432/arxiv_curator
      HF_TOKEN: ${HF_TOKEN}
      HF_MODEL: ${HF_MODEL:-facebook/bart-large-cnn}
      PYTHONUNBUFFERED: 1
    volumes:
      - ./src:/app/src
      - ./tests:/app/tests
      - ./volumes/logs:/logs
    command: python -m src.main

  web:
    build: .
    container_name: arxiv_web
    ports:
      - "5000:5000"
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      DATABASE_URL: postgresql://curator:${POSTGRES_PASSWORD:-secretpassword}@postgres:5432/arxiv_curator
      HF_TOKEN: ${HF_TOKEN}
      HF_MODEL: ${HF_MODEL:-facebook/bart-large-cnn}
      PYTHONUNBUFFERED: 1
    volumes:
      - ./src:/app/src
      - ./templates:/app/templates
      - ./static:/app/static
    command: python -m src.web_app

networks:
  default:
    name: arxiv-curator-network

volumes:
  postgres_data:
