version: '3.8'

services:
  postgres-test:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: arxiv_curator_test
      POSTGRES_USER: curator
      POSTGRES_PASSWORD: testpassword
    ports:
      - "5433:5432"

  tests:
    build: .
    depends_on:
      - postgres-test
    environment:
      DATABASE_URL: postgresql://curator:testpassword@postgres-test:5432/arxiv_curator_test
      HF_TOKEN: ${HF_TOKEN}
      PYTHONUNBUFFERED: 1
    volumes:
      - ./src:/app/src
      - ./tests:/app/tests
      - ./coverage:/app/coverage
    command: pytest -v --cov=src --cov-report=html:/app/coverage

networks:
  default:
    name: arxiv-curator-test-network
